language: swift
osx_image: xcode10
cache:
  - bundler
  - cocoapods
before_install:
  - bundle install
  - gem install linterbot
install:
  - gem install bundler -v 2.0.1
  - bundle update nokogiri
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
  - bundle install --path=vendor/bundle --jobs 4 --retry 3
script:
  - bundle exec pod install --repo-update 
  - ./scripts/linter